services:
  backend-api:
    #image: txhungg/langgraph-chatbot
    build: .
    container_name: langgraph-api
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    env_file: .env
    volumes:
      - ./models:/app/models         
      - ./connect_SQL/config.json:/app/connect_SQL/config.json
    ports:
      - "8000:8000"
    restart: always

  frontend-ui:
    #image: txhungg/langgraph-frontend
    build: .
    container_name: streamlit-ui
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend-api
    environment:
      - API_URL=http://backend-api:8000
    restart: always